#!/bin/bash
#
# iac_fuga
#
# Requirements: 
#
# Usage: iac_fuga [ -h | --help ] 
#
# Created: 2022/08/04
#
# Author: Leonardo José Nunes
#
# Version: beta
#
# License: MIT

[ "$1" = "-v" ] || [ "$1" = "--version" ] && {
  echo "beta"
  exit 0
}

[ "$1" = "-h" ] || [ "$1" = "--help" ] && {
  echo "
    Usage: iac_fuga ACTION... OPTION...

    # Folders:

    iac_fuga add folder                 # add folders and groups
    iac_fuga remove folder              # remove folders and groups
  "
  exit 0
}

# Source library
source ./src/lib/global_variables.sh          && \
source ./src/lib/check_config.sh              && \
source ./src/lib/global_functions.sh          && \
source ./src/actions/add/add_folder.sh        && \
source ./src/actions/remove/remove_folder.sh  \
|| {
  echo
  echo "Error getting source iac_fuga_lib.sh"
  echo
  exit 1
}

case "$1" in 
  add) 
    case "$2" in
      folder)
        add_folder
      ;;
    esac	
  ;;

  remove) 
    case "$2" in
      folder)
        remove_folder
      ;;
    esac	
  ;;

  *)
    echo "Invalid Option"
    echo "Try ./iac_fuga --help"

esac