#!/bin/bash
#
# iac_fuga
#
# Requirements: 
#
# Usage: iac_fuga [ -h | --help ] 
#
# Created: 2022/08/04
#
# Author: Leonardo José Nunes
#
# Version: beta
#
# License: MIT

[ "$1" = "-v" ] || [ "$1" = "--version" ] && {
  echo "beta"
  exit 0
}

[ "$1" = "-h" ] || [ "$1" = "--help" ] && {
  echo "
    Usage: iac_fuga ACTION... OPTION...

    # Folders:
    iac_fuga add folder         # add folder and groups
    iac_fuga remove folder      # remove folder and group
    iac_fuga install            # Install iac_fuga folders, groups and users on the OS
    iac_fuga uninstall           # uninstall iac_fuga from OS

    # Users:
    iac_fuga add user           # add user associated to groups
    iac_fuga remove user        # remove user 
  "
  exit 0
}

# Source library
source ./src/lib/global_variables.sh                && \
source ./src/lib/check_config.sh                    && \
source ./src/lib/global_functions.sh                && \
source ./src/actions/add/add_folder.sh              && \
source ./src/actions/remove/remove_folder.sh        && \
source ./src/actions/install/install_folder.sh      && \
source ./src/actions/uninstall/uninstall_folder.sh  && \
source ./src/actions/add/add_user.sh                && \
source ./src/actions/remove/remove_user.sh          && \
source ./src/actions/import/import_files.sh             \
|| {
  echo
  echo "Error getting source..."
  echo
  exit 1
}

case "$1" in 
  add) 
    case "$2" in
      folder)
        add_folder
      ;;

      user)
        add_user
      ;;

    *)
      echo "Invalid Option"
      echo "Try ./iac_fuga --help"
    esac	
  ;;

  remove) 
    case "$2" in
      folder)
        remove_folder
      ;;

      user)
        remove_user
      ;;

    *)
      echo "Invalid Option"
      echo "Try ./iac_fuga --help"
    esac	
  ;;

  install) 
  
    install_folder
    install_user
     
  ;;

  uninstall) 

    uninstall_folder
    uninstall_user

  ;;

  import) 

    import_files
     
  ;;

  *)
    echo "Invalid Option"
    echo "Try ./iac_fuga --help"

esac